// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PWSV.Infrastructure.Persistence;

#nullable disable

namespace PWSV.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PWSV.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AccountNumberCipher")
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<byte[]>("AccountNumberNonce")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AccountNumberTag")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Accounts_UserId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId"), new[] { "Name", "Balance" });

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_Accounts_UserId_IsActive");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasTrigger("trg_Accounts_PreventDeleteWhenHasTransactions");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PWSV.Domain.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AccountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH",
                            DisplayName = "Готівка"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BANK_CARD",
                            DisplayName = "Банківська картка"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CRYPTO",
                            DisplayName = "Криптогаманець"
                        },
                        new
                        {
                            Id = 4,
                            Code = "OTHER",
                            DisplayName = "Інше"
                        });
                });

            modelBuilder.Entity("PWSV.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditEntries_OccurredAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("IX_Categories_ParentCategoryId");

                    b.HasIndex("UserId", "Kind", "IsActive")
                        .HasDatabaseName("IX_Categories_UserId_Kind");

                    b.HasIndex("UserId", "ParentCategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories")
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_Kind", "[Kind] IN ('I','E')");
                        });
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currencies_DecimalPlaces", "[DecimalPlaces] BETWEEN 0 AND 8");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "UAH",
                            DecimalPlaces = (byte)2,
                            Name = "Українська гривня",
                            Symbol = "₴"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            DecimalPlaces = (byte)2,
                            Name = "Долар США",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EUR",
                            DecimalPlaces = (byte)2,
                            Name = "Євро",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PLN",
                            DecimalPlaces = (byte)2,
                            Name = "Польський злотий",
                            Symbol = "zł"
                        },
                        new
                        {
                            Id = 5,
                            Code = "GBP",
                            DecimalPlaces = (byte)2,
                            Name = "Фунт стерлінгів",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 6,
                            Code = "BTC",
                            DecimalPlaces = (byte)8,
                            Name = "Bitcoin",
                            Symbol = "₿"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ETH",
                            DecimalPlaces = (byte)8,
                            Name = "Ethereum",
                            Symbol = "Ξ"
                        },
                        new
                        {
                            Id = 8,
                            Code = "USDT",
                            DecimalPlaces = (byte)6,
                            Name = "Tether",
                            Symbol = "₮"
                        });
                });

            modelBuilder.Entity("PWSV.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("QuoteCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_ExchangeRates");

                    b.ToTable("ExchangeRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExchangeRates_DifferentCurrencies", "[BaseCurrencyId] <> [QuoteCurrencyId]");

                            t.HasCheckConstraint("CK_ExchangeRates_Rate", "[Rate] > 0");
                        });
                });

            modelBuilder.Entity("PWSV.Domain.Entities.KeyDerivationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Iterations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100000);

                    b.Property<int>("KeyLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(32);

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("KeyDerivationConfigs", (string)null);
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Counterparty")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("DescriptionCipher")
                        .HasMaxLength(2048)
                        .HasColumnType("varbinary(2048)");

                    b.Property<byte[]>("DescriptionNonce")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("DescriptionTag")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<long?>("LinkedTransactionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Transactions_CategoryId")
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.HasIndex("LinkedTransactionId")
                        .HasDatabaseName("IX_Transactions_LinkedTransactionId")
                        .HasFilter("[LinkedTransactionId] IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Transactions_OccurredAt");

                    b.HasIndex("AccountId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Transactions_AccountId_OccurredAt");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasTrigger("trg_Transactions_AfterDelete");

                            t.HasTrigger("trg_Transactions_AfterInsert");

                            t.HasTrigger("trg_Transactions_AfterUpdate");

                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Transactions_Kind", "[Kind] IN ('I','E','T')");

                            t.HasCheckConstraint("CK_Transactions_TransferShape", "([Kind] = 'T' AND [CategoryId] IS NULL) OR ([Kind] IN ('I','E') AND [CategoryId] IS NOT NULL)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PWSV.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(72)
                        .IsUnicode(false)
                        .HasColumnType("varchar(72)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Account", b =>
                {
                    b.HasOne("PWSV.Domain.Entities.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PWSV.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PWSV.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("PWSV.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Category", b =>
                {
                    b.HasOne("PWSV.Domain.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PWSV.Domain.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("PWSV.Domain.Entities.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PWSV.Domain.Entities.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.KeyDerivationConfig", b =>
                {
                    b.HasOne("PWSV.Domain.Entities.User", "User")
                        .WithOne("KeyDerivationConfig")
                        .HasForeignKey("PWSV.Domain.Entities.KeyDerivationConfig", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PWSV.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PWSV.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PWSV.Domain.Entities.Transaction", "LinkedTransaction")
                        .WithMany()
                        .HasForeignKey("LinkedTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("LinkedTransaction");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PWSV.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Categories");

                    b.Navigation("KeyDerivationConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
